on:
  push:
    branches:
      - main
name: release
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: simple
          package-name: la-ctl
      - uses: actions/checkout@v3
        if: ${{ steps.release.outputs.release_created }}
      - uses: cachix/install-nix-action@v18
        if: ${{ steps.release.outputs.release_created }}
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v12
        if: ${{ steps.release.outputs.release_created }}
        with:
          name: klarkc
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix build
        if: ${{ steps.release.outputs.release_created }}
